### ISSUE TITLE
Testing ChameleonMiniLiveDebugger

### ISSUE THREAD

**Issue by gtpy** [maxieds/ChameleonMiniLiveDebugger#1]
I’ll have done some first checks of your app.
It looks nice.
Some little things can be added:

Similar functions like in a serial terminal like this:
<img src='http://up.picr.de/31446710kr.jpg' border='0' alt='Bild'/>

f.e. change settings, query actual setting, query actual config, ...
Would be great if you can add some like these functions.
(Here some example commands from my mobile terminal)

Why you only have under configure minimal peripherals only rbuttonlong and not the lbutton, lbuttonlong,...

[#159](https://github.com/emsec/ChameleonMini/issues/159)

Cheers

**Comment by maxieds** [comment]
Ok, I will work on adding some of your suggestions. I have comp exams this week and next which are taking precedence over all for now. So it might be a little while before I get back into coding. 

I just added the two so as not to clutter up the already large tools menu interface too much. It’d easy to add them all. I’ll put it on my todo list.

What do you think about the current APDU command recognition? Is it accurate enough, or still needs some improvement?

**Comment by gtpy** [comment]
Hi @maxieds 
I've performed some small tests.
Your app crashes when screen rotates - so i need to turn off screen rotation before usage.
Logged 3 different connections and like the output of your log-export.

**Comment by maxieds** [comment]
Would you add the screen rotation bug to the issues page on my GitHub site
for the app so I remember to fix it? I'm sure I can have the app turn this
off by default so you don't have to.

Are you finding the apdu command recognition to be accurate, or do you
think it still needs work?

Maxie

**Comment by maxieds** [comment]
Sorry, I guess you already did this. I was expecting it to be from the CM issues site on my email. :)

**Comment by maxieds** [comment]
The screen rotation issue is fixed in the development version. I will roll out a new release on the Play Store later tonight (US Eastern time).

**Comment by gtpy** [comment]
Thanks. I'll test deeper if I find more time between work and family.
I think to find some time at work to play around with the chameleon and your app
I'll give you an update when I looked at apdu command and more ;-)

**Comment by maxieds** [comment]
The [newest live version in the Play Store](https://play.google.com/store/apps/details?id=com.maxieds.chameleonminilivedebugger) should incorporate several of your suggestions. It also fixes the screen rotation issue in the software without the user having to to it. Let me know what you think when you have some more time to test it out. 

@doegox: I noticed that you starred the repo and are located in Brussels, so I added a roll out in Belgium for you to use without having to proxy through an install. Please also give me your feed back on the new release.

**Comment by doegox** [comment]
Excellent thank you @maxieds !
I tried briefly with a OnePlus 5, a USB-C OTG and the usual USB micro cable and it can communicate properly with the Chameleon Mini (once OTG storage is activated in the parameters of course).
The few issues I had yesterday seem to be already solved in today version, nice :) (log tab empty, second instance launched on re-plug/reset,...)

**Comment by doegox** [comment]
How do we see the result of a command? E.g. using the "(Almost) Complete Shell / LEDRED?" I see in the log tab "INFO: shell command of ledred? returned status 101:ok with text" but I don't see the expected text.
Also when I press the predefined command buttons (charging, identify,...) I don't see any effect, no result, nothing in the log tab.

**Comment by doegox** [comment]
FYI for those having a phone with USB-C, I received today this cable https://www.amazon.fr/gp/product/B071H6ZW6Y and it works very nicely.

**Comment by maxieds** [comment]
The output of the command should be directly underneath the header (if
there is any to display). I found a couple more bugs, so I will release a
newer version this morning. I'm glad you're enjoying the newer release.

I still don't know how to fix the blank tabs when the app relaunches
because usb is plugged in. Something weird is going on with the way the USB
intent handlers are getting registered. It's on my list of bugs to fix, but
for now if it happens just restart the app.

Maxie

**Comment by maxieds** [comment]
A new release (0.0.8-v1) should be out soon. It features improved APDU command recognition and some bug fixes. Thanks for helping me test it!

**Comment by doegox** [comment]
on the new version (0.0.8) peripherals and log mode, we don't see anymore the initial status of all leds & buttons. It was properly displayed in 0.0.6

**Comment by maxieds** [comment]
I'm going to have to fix this later this afternoon. Let me know if the new
release broke anything else.

Maxie

**Comment by maxieds** [comment]
Here's a more recent screen shot of what the app looks like now. Thanks to @doegox for all of the suggestions. I'm going to roll out another release on play store once I figure out how to get this really annoying blank tabs after USB connect issue fixed. Look out for it tomorrow morning. 
![screenshot_20180110-225705](https://user-images.githubusercontent.com/22165688/34808030-13ba0e44-f65a-11e7-8893-7ec49bbfcee5.png)

**Comment by maxieds** [comment]
I'm going to close the issue since it seems that all of the original requests have been handled. Please post new issue threads for future feature requests in the app. I'd like to see more of them.
